apiVersion: v1
kind: Secret
metadata:
  name: sprint9-dwh-secrets
type: Opaque
stringData:
  # Kafka
  KAFKA_CONSUMER_USERNAME: ""
  KAFKA_CONSUMER_PASSWORD: ""

  # Postgres
  PG_WAREHOUSE_PASSWORD: ""

